# project definitions
project: kover_0.1
audience: writers
product: all
platform: all
version: all
destination: ../doc_writers
topnav_title: Kover Documentation
homepage_title: Kover Documentation
site_title: Kover Documentation
disqus_shortname:
google_analytics:
github_editme_path: #aldro61/kover/blob/gh-pages
# don't use a slash before or after the above path. here's how this url gets written out in page.html: https://github.com/{{site.github_editme_path}}{{page.url | replace: '.html', '.md'}}

# variables

sidebar_tagline: <img src="images/logo_sidebar.png">
sidebar_version: v2.0.0
theme_file: theme-blue.css
project_file_name: doc

port: 4003
exclude:
  - configs/
  - _site
  - _drafts
  - di_multi*

# same for all
host: 127.0.0.1
feedback_email: aldro61@gmail.com
sidebar_accordion: true
markdown: redcarpet
print: false

# only use suffix if you need to force index.html to display
# suffix: index.html

highlighter: pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true


